### ISSUE TITLE
[FEAT] NeRF 개발환경과 NeRF studio를 통해 Custom dataset으로 학습한 nerf

### ISSUE THREAD

**Issue by tosemfdk** [NeRFs-Eye-View/nerf-project#22]
## Description
- Nerf의 개발환경의 문제점과 NeRF studio를 통해 Custom dataset으로 nerf를 학습시키고 이를 랜더링한다..

## PPT

[드림학기 발표 3:22(화) Nerf custom dataset.pdf](https://github.com/NeRFs-Eye-View/nerf-project/files/14720493/3.22.Nerf.custom.dataset.pdf)

**Comment by jungcow** [comment]
피드백 
- GPU 환경을 구축하기 위해 필요한 것들을 알아볼 것.
